version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./template:/etc/nginx/nginx.conf
      - ./server.crt:/ssl/server.cert
      - ./server.key:/ssl/server.key
    networks:
      - dalmaf-webapp_infraserver

  rest_server:
    build:
      dockerfile: "Dockerfile"
      context: "."
    container_name: hapijs
    restart: unless-stopped
    networks:
      - dalmaf-webapp_infraserver

networks:
    dalmaf-webapp_infraserver:
      external: true
